/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as DashboardHomeRouteImport } from './routes/dashboard.home'
import { Route as DashboardResumeIdIndexRouteImport } from './routes/dashboard.resume.$id.index'
import { Route as DashboardResumeIdPatchPatchIdRouteImport } from './routes/dashboard.resume.$id.patch.$patchId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeIdIndexRoute = DashboardResumeIdIndexRouteImport.update({
  id: '/resume/$id/',
  path: '/resume/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeIdPatchPatchIdRoute =
  DashboardResumeIdPatchPatchIdRouteImport.update({
    id: '/resume/$id/patch/$patchId',
    path: '/resume/$id/patch/$patchId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/home': typeof DashboardHomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/resume/$id/': typeof DashboardResumeIdIndexRoute
  '/dashboard/resume/$id/patch/$patchId': typeof DashboardResumeIdPatchPatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/home': typeof DashboardHomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/resume/$id': typeof DashboardResumeIdIndexRoute
  '/dashboard/resume/$id/patch/$patchId': typeof DashboardResumeIdPatchPatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/home': typeof DashboardHomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/resume/$id/': typeof DashboardResumeIdIndexRoute
  '/dashboard/resume/$id/patch/$patchId': typeof DashboardResumeIdPatchPatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/home'
    | '/sign-in/$'
    | '/dashboard/resume/$id/'
    | '/dashboard/resume/$id/patch/$patchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/home'
    | '/sign-in/$'
    | '/dashboard/resume/$id'
    | '/dashboard/resume/$id/patch/$patchId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/home'
    | '/sign-in/$'
    | '/dashboard/resume/$id/'
    | '/dashboard/resume/$id/patch/$patchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume/$id/': {
      id: '/dashboard/resume/$id/'
      path: '/resume/$id'
      fullPath: '/dashboard/resume/$id/'
      preLoaderRoute: typeof DashboardResumeIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume/$id/patch/$patchId': {
      id: '/dashboard/resume/$id/patch/$patchId'
      path: '/resume/$id/patch/$patchId'
      fullPath: '/dashboard/resume/$id/patch/$patchId'
      preLoaderRoute: typeof DashboardResumeIdPatchPatchIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardResumeIdIndexRoute: typeof DashboardResumeIdIndexRoute
  DashboardResumeIdPatchPatchIdRoute: typeof DashboardResumeIdPatchPatchIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardResumeIdIndexRoute: DashboardResumeIdIndexRoute,
  DashboardResumeIdPatchPatchIdRoute: DashboardResumeIdPatchPatchIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
